### PR TITLE
build script for vscode, no postfix

### PR DESCRIPTION
**Pull request by theTonyHo**
Added a build script for VSCode
Was there a reason for the postfix ? Having the postfix did not work for VSCode so I created a separate build script

### CODE REVIEW

**Comment by sbaer** [comment]
This seems like the same powershell script as what already exists. I'm confused as to what this is for.

**Comment by theTonyHo** [comment]
The script is specific to VSCode users
It builds without the postfix `-stubs`

I don't have PyCharm installed, so I could not confirm if it work for PyCharm.
It would be good if having no postfix works for all IDE.

**Comment by sbaer** [comment]
-stubs is what all of the packages on pypi are named with and appears to be the common practice for packages that don't have any real content other than type information.

https://pypi.org/search/?q=stubs

I don't think we want to change this

**Comment by theTonyHo** [comment]
Ah I see, it makes sense.

We can disregard this PR

**Pull request closed without merging**
